name: Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run Tests
      run: |
        npm install 
        npm run test --coverage
        